/**
 * Created by aitor on 14/12/14.
 */

define({
    new_game: 'Nueva partida',
    game_data: 'Datos de la partida',
    num_players: 'Número de Jugadores',
    player: "Jugador",
    players: "Jugadores",
    game_mode: "Modo de juego",
    clasic: "Clásico",
    cut_throat: "En contra",
    name_player: "Nombre del Jugador",
    play: "Jugar",
    attempt_data: "Datos de la tirada",
    playerTurn: " es tu turno!",
    first_attempt: "Primera tirada",
    second_attempt: "Segunda tirada",
    third_attempt: "Tercera tirada",
    sector: "Sector",
    results: "Resultados",
    nothing: "Agua",
    bull: "Diana",
    type: "Tipo",
    simple: "Simple",
    double: "Doble",
    triple: "Triple",
    next: "Siguiente",
    points: "Puntos",
    failures: "Fallos",
    congratulations: "Felicidades",
    you_win: "Has ganado!",
    history: "Historial",
    show_histoy: "Mostrar el Historial",
    show_game: "Mostrar el Juego",
    no_history: "Todavía no se han realizado movimientos.",
    restore: "Restaurar",
    attemptSummary: "Resumen de la tirada",
    correct: "Guardar",
    rectify: "Modificar",
    attemptNum: "Tirada nº",
    information: "Información:",
    round: "Ronda",
    language: "Idioma"
});