/**
 * Created by aitor on 14/12/14.
 */

define({
    new_game: 'Nova partida',
    game_data: 'Dades de la partida',
    num_players: 'Numero de jugadors',
    player: "Jugador",
    players: "Jugadors",
    game_mode: "Mode de joc",
    clasic: "Clásic",
    cut_throat: "En contra",
    name_player: "Nom del Jugador",
    play: "Jugar",
    attempt_data: "Dades de la tirada",
    playerTurn: " es el teu torn!",
    first_attempt: "Primera tirada",
    second_attempt: "Segona tirada",
    third_attempt: "Tercera tirada",
    sector: "Sector",
    results: "Resultats",
    nothing: "Aigua",
    bull: "Diana",
    type: "Tipus",
    simple: "Simple",
    double: "Doble",
    triple: "Triple",
    next: "Següent",
    points: "Punts",
    failures: "Errors",
    congratulations: "Felicitats",
    you_win: "Ha guanyat!",
    history: "Historial",
    show_histoy: "Mostrar el Historial",
    show_game: "Mostrar el Joc",
    no_history: "Encara no s'han realitzat moviments.",
    restore: "Restaurar",
    attemptSummary: "Resum de la tirada",
    correct: "Guardar",
    rectify: "Modificar",
    attemptNum: "Tirada nº",
    information: "Informació:",
    round: "Ronda",
    language: "Idioma"
});