/**
 * Created by aitor on 22/3/15.
 */

define({
    "root": {
        new_game: 'New game',
        game_data: 'Game Details',
        num_players: 'Number of Players',
        player: "Player",
        players: "Players",
        game_mode: "Game mode",
        clasic: "Clasic",
        cut_throat: "Cut throat",
        name_player: "Player Name",
        play: "Play!",
        attempt_data: "Details attempt",
        playerTurn: " it's your turn!",
        first_attempt: "First attempt",
        second_attempt: "Second attempt",
        third_attempt: "Third attempt",
        sector: "Sector",
        results: "Results",
        nothing: "Fail",
        bull: "Bull",
        type: "Tipo",
        simple: "Simple",
        double: "Double",
        triple: "Triple",
        next: "Next",
        points: "Points",
        failures: "Failures",
        congratulations: "Congratulations",
        you_win: "You won!",
        history: "History",
        show_histoy: "Show History",
        show_game: "Show the game",
        no_history: "Has not yet been made movements.",
        restore: "Restore",
        attemptSummary: "Summary attempt",
        correct: "Save",
        rectify: "Modify",
        attemptNum: "Attempt #",
        information: "Information:",
        round: "Round",
        language: "Language"
    },
    "es-ES": true,
    "ca-ES": true
});